/*
 * (c) Copyright 2005-2013 JAXIO, http://www.jaxio.com
 * Source code generated by Celerio, a Jaxio product
 * Want to purchase Celerio ? email us at info@jaxio.com
 * Follow us on twitter: @springfuse
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Template pack-backend-jpa:src/main/java/repository/Repository.e.vm.java
 */
package repository.Test;


import domain.Test.Personnel;
import org.springframework.cache.annotation.Cacheable;
import repository.support.GenericRepository;

import javax.inject.Named;
import javax.inject.Singleton;
import javax.persistence.Query;
import java.util.List;

@Named
@Singleton
public class TestRepository extends GenericRepository<Personnel> {


    public TestRepository() {
        super(Personnel.class);
    }

    @Cacheable(value = "testCache")
    public Personnel testCache(int i, int j) {
        Personnel p =new Personnel();
        p.setLastName("i="+i);
        p.setFirstName("j="+j);
        System.out.println("test cacheCalled for"+i +"and "+ j);
        return p;
    }

}